### PR TITLE
use tl.writeFile() to allow mocking for L0 tests

### PR DESCRIPTION
**Pull request by madhurig**

### CODE REVIEW

**Comment by DavidStaheli** [comment]
Looks good.

**Comment by bryanmacfarlane** [comment]
Yep.  Just need to adjust couple comments in task lib change, then I will publish then this can react and go in.

**Comment by madhurig** [comment]
@bryanmacfarlane : Task lib changes and reaction are done

**Comment by bryanmacfarlane** [comment]
lib is published.

BTW, I think you added the file tests in the localization suite :)

**Comment by madhurig** [comment]
Thanks for publishing the lib. I see the tests now, I added them after exists() tests which are also in the Localization suite. I will move both out of there :)

**Pull request merged**
