### PR TITLE
[ServiceFabricComposeDeploy] Sanitize compose application name for SDK version >= 2.8

### LINKED ISSUE #6559: [Service fabric compose deploy] Should not use "fabric:/" with for application name for SDK >= 2.8
With SDK 2.8+ compose application deployment fails if application name contains any character which is invalid for DNS name. We need to remove "fabric:/" prefix in such case.
No need to update release template as it should still support SDK < 2.8

### PR DESCRIPTION
**Pull request by bishal-pdMSFT**
Fixes #6559

### CODE REVIEW

**Comment by bishal-pdMSFT** [comment]
Please review

**Comment by bishal-pdMSFT** [comment]
Your concern is valid, but there is not much we can do as platform has a breaking change. I have put a warning message to let user know of this change. Also, since this feature is in preview, we have an excuse to do this.

Other option is to check application name and keep failing with a better message. Let user take corrective action. I am fine with this approach as well.

**Comment by NCarlsonMSFT** [comment]
I prefer this approach as it will be best for the majority. Mainly mentioned the concern out of completeness.

**Comment by bishal-pdMSFT** [comment]
@NCarlsonMSFT , I had discussion with Pulkit and @sachinma regarding this and a concern was raised that even though we will get the application to get installed successfully with a sanitized name, it might not be an expected behavior for user. There could be unexpected failures for user in consuming this application e.g. a test which depends on application name will start failing, or some other application will not be able to communicate with this application.
In light of these, we feel that it might be better to just show a more meaningful warning message to user at the start of task - telling that task might fail as application name contains 'fabric:/'

**Comment by NCarlsonMSFT** [comment]
@bishal-pdMSFT seems reasonable. Would this just be a warning, or would the task block the user?

**Comment by bishal-pdMSFT** [comment]
This will just be a warning. Let platform fail or not fail.

**Comment by bishal-pdMSFT** [comment]
@NCarlsonMSFT I have updated PR. Please take a look.

**Pull request merged**
