### PR TITLE
Updating VSTS Task Lib in PowerShellV2 task to eliminate environment block size error

### PR DESCRIPTION
**Pull request by jkanczler**
Updated the version of VstsTaskSdk (powershell) from 0.9.0 to 0.11.0.
Updated the version of vsts-task-lib from 2.0.5 to 2.6.0.

The reason: environment variable block size issue was fixed in July 2017 in vsts-task-lib. See here: Microsoft/vsts-task-lib#228

VstsTaskSdk 0.9.0 was released in June 2017.
vsts-task-lib 2.0.5 was released in April 2017.

Updating the dependencies should fix the issue: Microsoft/vsts-tasks#7824.

### CODE REVIEW

**Comment by jkanczler** [comment]
@ericsciple or @stephenmichaelf, could you review my changes?

**Comment by stephenmichaelf** [comment]
Thanks for the contribution! Can you update the two 137 values to 140? It matches our current sprint. Thanks

**Comment by jkanczler** [comment]
Version is updated to correctly represent the current sprint.

**Comment by bryanmacfarlane** [comment]
We should take this

**Pull request merged**
