### PR TITLE
PowerShellV2 task: Add checkbox (not ticked by default) in advanced section to optionally run PowerShell Core on Windows

### LINKED ISSUE #7461: PowerShell v2 task to have option to run PowerShell Core on Windows as well
If the PowerShell v2 task runs on Linux/Mac it uses PowerShell Core automatically but on Windows, it uses Windows PowerShell.
There should be something like a checkbox available to `Run using PowerShell Core` that makes it use PowerShell Core on Windows and the value of this checkbox gets ignored on other systems.

### PR DESCRIPTION
**Pull request by bergmeister**
Resolves #7461 by adding a checkbox to optionally use `pwsh.exe` as an entry assembly for the PowerShell V2 task on Windows
This supersedes PR #7797, which hasn't progressed in the last 2 weeks.
I ran the test suite locally using `npm install; node make.js build --task PowerShellV2; node make.js test --task PowerShellV2` and all 9 L0 tests passed.
cc @ericsciple

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@bergmeister can you resolve the merge conflict?  @ericsciple can you have someone review?  Thanks!

**Comment by SteveL-MSFT** [comment]
@ericsciple I think strict check making it declarative would lead to less hard to troubleshoot issues in the future

**Comment by bergmeister** [comment]
@ericsciple I resolved the merge conflict and renamed the input parameter `preferPwsh` to `pwsh` as requested. For minor details like e.g. the wording, feel free to just push your own changes.

**Comment by ericsciple** [comment]
thanks!

**Comment by ericsciple** [comment]
@stephenmichaelf can you follow through on this? Let's chat tomorrow, I can relay details.

**Comment by stephenmichaelf** [comment]
Got it.

**Comment by bergmeister** [comment]
@ericsciple  @stephenmichaelf How can I follow the release process of this (do I watch a certain branch?) or get notified once this gets released so that I don't have to keep checking?

**Comment by kilasuit** [comment]
Indeed I'm currenty looking to make use of this too

**Comment by TomasHubelbauer** [comment]
How can I use this in YAML? I tried:

```yml
- powershell: |
   echo "test"
  pwsh: true
```

But it throws: azure-pipelines.yml (Line: 10, Col: 3): Unexpected value 'pwsh'

**Comment by TomasHubelbauer** [comment]
I think `pwsh` should be another shorthand, for Powershell Core. I created #9496 to suggest that.

**Comment by bergmeister** [comment]
I like that suggestion even more, I will raise also raise the issue of the `view yaml` button not working for the inlinescripts option of v1 and v2 of the PowerShell task

**Pull request merged**
