### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
I'm not sure what your requirements are for PRs, I can rearrange these/fold as requested...

### CODE REVIEW

**Comment by mvvsubbu** [comment]
Can you update the PR with latest merge from master, to resolve conflicts so that I can go ahead to merge

**Comment by jsoref** [comment]
@mvvsubbu : done...

**Comment by bryanmacfarlane** [comment]
@mvvsubbu - what is going on with this PR?  it now has conflicts again.  take or close

**Comment by jsoref** [comment]
@bryanmacfarlane, @mvvsubbu : updated...

**Pull request merged**
