### PR TITLE
Increased inline powershell script maxLength to an unlimited size for…

### PR DESCRIPTION
**Pull request by icnocop**
… more flexibility

### CODE REVIEW

**Comment by ericsciple** [comment]
@chrisrpatterson to comment, I believe the limitation is intentional and larger scripts should be checked-in.

**Comment by icnocop** [comment]
I recommend leaving that decision to the developer for flexibility reasons.
For example, I may want to build code in a repository that I only have read-only access for.
Another example is if I want to build an older version of the repository, where the powershell script has not been checked in, or is an older version that no longer works for whatever reason.

**Comment by bryanmacfarlane** [comment]
For the scenarios you mention, in the powershell script task, you can specify any location.  It does not have to be a repo location.  For example, you can put in the location of a share.

This option was created for quick little snippets - not to be a coding environment.

**Comment by icnocop** [comment]
I am using Visual Studio Team Services and it doesn't seem practical to have a dependency on an external file if I need 501 characters in a powershell script for example. If the first time a powershell script task works and requires less than 500 characters, great. But in a subsequent iteration, if the build step needs to do more things and exceeds 500 characters, the developer may do even worse things like make the code (ex. variable names) unreadable. If the powershell script task gets too long, maybe we can just display a warning and indicate a recommend solution. Why impose limitations on the build and on the developer? Please let the developer decide what's best for the build at the time. Let the developer decide when a good time is to move to an external file if/when needed/desired.

**Comment by bryanmacfarlane** [comment]
Because once you're beyond a block of inline and into a long file expectations change.  At that point it's a coding environment when you're coding long files

It's not arbitrary.

**Comment by icnocop** [comment]
500 is arbitrary.

Let the developer decide what the limitations and expectations are, and not the tool.

**Comment by bryanmacfarlane** [comment]
a specific number is but the choice to limit it to something reasonable that is not optimized for in the task model and views is not.  The use case for this was I only have a few lines and I don't want to check in a file.  Once you're writing very large files you need the Monaco editor and history.

We have another feature on the backlog for additional repos outside your main repos so you can keep scripts out of source, not in a share, in the cloud and use the web editor and history

In the meantime, if you really want to do this then create your own task.  But be aware that we haven't optimized for very large task inputs throughout

**Pull request closed without merging**
