### PR TITLE
Removed BYOS option for JMeter task

### PR DESCRIPTION
**Pull request by cltshivash**
Removed BYOS option for JMeter task

### CODE REVIEW

**Comment by nigurr** [comment]
This will not go in current sprint rollout?

**Comment by ptoonen** [comment]
@cltshivash why was this option removed?

**Comment by cltshivash** [comment]
@ptoonen There are open questions around the business model that needs to be closed.

**Comment by glloyd2010f** [comment]
@cltshivash What is the status of the re-adding custom agents for jmeter tests? Is there a road map for this? We have internal tests that we were planning to move to VSTS and now can't since this functionality has been removed.

**Pull request closed without merging**
