### PR TITLE
Bug fix 584674

### PR DESCRIPTION
**Pull request by kaadhina**
Porting fix from master

### CODE REVIEW

**Comment by kaadhina** [comment]
Validations: Manual
There are already UTs in master

**Comment by nigurr** [comment]
Approved

**Comment by kaadhina** [comment]
Is the fix already in master? Yes
What testing was done? Manual, UTs
Does this fix change the AT/DT contract? No
Were tests added to cover this to make sure it doesn't regress? Yes

**Comment by kaadhina** [comment]
Is this a regression? : No

**Comment by kaadhina** [comment]
Will be updating additional dependencies xml in mseng, post this.

**Pull request closed without merging**
