### PR TITLE
Allow NuGet tasks to work in Release Management 

### PR DESCRIPTION
**Pull request by zarenner**
…by using System.DefaultWorkingDirectory instead of Agent.BuildDirectory

### CODE REVIEW

**Comment by zarenner** [comment]
@jmyersmsft

**Comment by jmyersmsft** [comment]
:shipit:

**Comment by jmyersmsft** [comment]
Actually, this needs a version bump to the tasks, and needs to be ported to releases/m103

**Comment by jmyersmsft** [comment]
Superseded and merged as #2154

**Pull request closed without merging**
