### PR TITLE
Do not add extra quotes on the SonarQube arguments passed to Maven.

### PR DESCRIPTION
**Pull request by bgavrilMS**

### CODE REVIEW

**Comment by madhurig** [comment]
Looks good, the task lib change allows the task code to be cleaner

**Comment by bryanmacfarlane** [comment]
Looks good.  Leaving to you to actually test @ runtime.

Make sure you cherry pick to releases/m99 in the event a new patch goes out

**Comment by bgavrilMS** [comment]
@madhurig  I actually forgot to bump the task version, I will do this now. 

@bryanmacfarlane - for releases/m99 - would I need to also  bump the task version there and re-package the tasks?

**Comment by ericsciple** [comment]
Yes bump the patch version also. I'll go ahead and bump the externals after your changes are merged.

**Pull request merged**
