### PR TITLE
Create task.json documentation.md

### PR DESCRIPTION
**Pull request by wfoster232**
New help documentation for the task.json file

### CODE REVIEW

**Comment by wfoster232** [comment]
Done :)

**Comment by kmkumaran** [comment]
@bryanmacfarlane you might want to accept or close.

**Comment by wfoster232** [comment]
Hi,

Is anyone still looking at this PR? - it is now the oldest in the backlog of PR's and I believe it offers considerable value from a 'how-to' perspective - especially of value to in-house TFS implementations.

Thanks

**Comment by bryanmacfarlane** [comment]
Yes, we are looking at it.  We have a story soon to document this and other task info but we are likely going to solve it a slightly different way.  We want to publish a json schema, have docs point to that and integrate it into the tooling.  I'm leaving this open till we get to that ( soon )

**Comment by AArnott** [comment]
@bryanmacfarlane: I want a schema so bad... I'm writing one. I hope you'll accept a PR for that. :)

**Comment by AArnott** [comment]
I submitted #2655 to deliver the actual JSON schema.

**Comment by bryanmacfarlane** [comment]
Closing this out since Andrew has the schema.  We will take that.

**Pull request closed without merging**
