### PR TITLE
[Xcode] Add the Additional command line arguments to the package app phase

### PR DESCRIPTION
**Pull request by vkedwardli**
Currently the additional arguments are not injected into the package app phase, so it is not possible to define preprocessing macros by specifying `OTHER_SWIFT_FLAGS` or `SWIFT_ACTIVE_COMPILATION_CONDITIONS`

### CODE REVIEW

**Comment by vkedwardli** [comment]
@madhurig possible to review this? thanks

**Comment by madhurig** [comment]
@vkedwardli : Thank you for the contribution!

**Comment by madhurig** [comment]
@vkedwardli: I am reverting this change since it is causing test failures. Will review and include the changes. If you have time please fix the tests. Otherwise, I will do it later this week.

**Comment by madhurig** [comment]
@vkedwardli: PR for fixing the test: https://github.com/Microsoft/vsts-tasks/pull/5481

**Pull request merged**
