### PR TITLE
use renamed vsts-task-lib

### PR DESCRIPTION
**Pull request by jasonnian1978**

### CODE REVIEW

**Comment by jasonnian1978** [comment]
[Uploading audacity-win-2.1.2.zip…]()
[Uploading Markdown_1.0.1.zip…]()
[Uploading vscode-master.zip…]()

**Comment by jasonnian1978** [comment]
[Uploading Startupizer2.zip…]()

**Comment by bryanmacfarlane** [comment]
vsts tasks master has already renamed to vsts task lib.

**Comment by jasonnian1978** [comment]
Thanks

发自我的 iPhone

**Pull request closed without merging**
