### PR TITLE
Support SonarQube project fields in Maven task

### PR DESCRIPTION
**Pull request by DavidStaheli**
This adds SonarQube project fields to Maven, just like exist in Gradle.  The code in the CodeAnalysis folder of Maven already supports these fields.  This PR just exposes them in the UI.  The fields are not required, so compatibility is maintained.

### CODE REVIEW

**Comment by madhurig** [comment]
Looks good to me

**Comment by bryanmacfarlane** [comment]
merge?

**Comment by DavidStaheli** [comment]
Not yet

**Comment by DavidStaheli** [comment]
We're waiting on final testing at a customer site.  We plan to merge before the end of S116 (April 14).

**Pull request merged**
