### PR TITLE
Remove deprecated task: XamarinComponentRestoreV0 and XcodePackageiOSV0

### PR DESCRIPTION
**Pull request by joshmgross**
Removed XamarinComponentRestoreV0 and XcodePackageiOSV0 since they have been deprecated. Tasks have already been extracted and pushed to nuget feeds (See @stephenmichaelf )

### CODE REVIEW

**Comment by stephenmichaelf** [comment]
You will also want to remove them from make-options:

https://github.com/Microsoft/vsts-tasks/blob/master/make-options.json#L115
https://github.com/Microsoft/vsts-tasks/blob/master/make-options.json#L119

Were you able to get access to the repo?

**Comment by joshmgross** [comment]
No I don't have access to the repo yet

**Comment by madhurig** [comment]
@stephenmichaelf: Please enable checks to run from PR forks as well.

**Comment by joshmgross** [comment]
Moving to #8257 for checks

**Pull request closed without merging**
