### PR TITLE
Update 'runsOn' to include Deployment Groups.

### PR DESCRIPTION
**Pull request by kuvinodms**
This change has been done in order to fix the following issue:
https://github.com/Microsoft/vsts-tasks/issues/5097

Changes has been copied from the following commit:
https://github.com/Microsoft/vsts-tasks/pull/5098/commits/f467004c59b914e440f19d09fda0f1c1be8aaa86

Customer is not responding and we are unable to cherry-pick customer's commit due to different Repos, hence copied the changes on my own.

Would like to get comments if you have questions over significance of this change.

### CODE REVIEW

**Comment by chrisrpatterson** [comment]
Running a service fabric compose deploy from a deployment group does not seem to be a valid scenario.  Can you comment on why you might need to do this?

**Comment by kuvinodms** [comment]
Hey Chris,

Customer has mentioned the scenario in the issue https://github.com/Microsoft/vsts-tasks/issues/5097, please have a look and reply for the same.

Regards,
Vinod

**Comment by kuvinodms** [comment]
@chrisrpatterson 
Awaiting for your response.

**Comment by bishal-pdMSFT** [comment]
@kuvinodms please merge this.

**Pull request merged**
