### PR TITLE
Updating Jacoco version to 0.8.1

### PR DESCRIPTION
**Pull request by kelliejos**
Updating the Jacoco version we use in our codecoverage tools to newest version.

Tested in dev environment and via running unit tests.

### CODE REVIEW

**Comment by lkillgore** [comment]
Gradle?

**Comment by kelliejos** [comment]
I checked about that. We don't seem to specifically set the Jacoco version in the Gradle code.

**Comment by kelliejos** [comment]
When I spoke to Eric and Stephen last, they told me the package-lock files get checked in. @lkillgore do you know if that is still the case?

**Comment by lkillgore** [comment]
As far as Gradle goes, doesn't it use `codecoverage-tools`?  If you're changing that, do you want that change to be included with the Gradle task?  Or is it unaffected?

**Comment by kelliejos** [comment]
We do not set the jacoco version for the gradle task, so we don't need to do any updates here.

**Pull request merged**
