### PR TITLE
Update link to NuGet doc site.

### PR DESCRIPTION
**Pull request by pascalberger**
Update links to fit to the new NuGet doc site.

### CODE REVIEW

**Comment by pascalberger** [comment]
@bryanmacfarlane Any interest in this? If so I can rebase otherwise I will close the PR

**Comment by bryanmacfarlane** [comment]
Take it or close it

**Comment by pascalberger** [comment]
@bryanmacfarlane Rebased and updated links to docs.microsoft.com

**Comment by bryanmacfarlane** [comment]
@keithrob and @alexmullans - can you review please?

**Pull request merged**
