### PR TITLE
Improve markdown for CopyFiles tag

### PR DESCRIPTION
**Pull request by pascalberger**
Mention that copy files work also with UNC paths as target and reword so that it is clear that variables are optional.

### CODE REVIEW

**Comment by TingluoHuang** [comment]
Please use gulp build the repository, push all generated changes. the changes looks good to me.

**Comment by pascalberger** [comment]
@TingluoHuang I already build and added the res file. What are you missing?

**Comment by pascalberger** [comment]
@TingluoHuang You're still interested in this? If so I can put some effort into it to fix the conflicts otherwise I will close the PR.

**Comment by kmkumaran** [comment]
@bryanmacfarlane assigning to you to accept/close accordingly.

**Comment by pascalberger** [comment]
@bryanmacfarlane Any opinion about this?

**Comment by bryanmacfarlane** [comment]
sorry for delay.  If u want to resolve conflicts, we will take.

**Comment by pascalberger** [comment]
@bryanmacfarlane Done. Also incremented task version and recreated generated files.

**Pull request merged**
