### PR TITLE
Fix arg inputs.

### PR DESCRIPTION
**Pull request by ericsciple**

### CODE REVIEW

**Comment by jabjohanna** [comment]
Error..
2016-05-04T20:26:33.4938388Z C:\AgentRunProvisioning\tasks\Npm\0.2.12\npmtask.js:3
2016-05-04T20:26:33.4938388Z const path = require('path');
2016-05-04T20:26:33.4938388Z ^^^^^
2016-05-04T20:26:33.4938388Z SyntaxError: Use of const in strict mode.
2016-05-04T20:26:33.4938388Z     at exports.runInThisContext (vm.js:73:16)
2016-05-04T20:26:33.4938388Z     at Module._compile (module.js:443:25)
2016-05-04T20:26:33.4938388Z     at Object.Module._extensions..js (module.js:478:10)
2016-05-04T20:26:33.4938388Z     at Module.load (module.js:355:32)
2016-05-04T20:26:33.4938388Z     at Function.Module._load (module.js:310:12)
2016-05-04T20:26:33.4938388Z     at Function.Module.runMain (module.js:501:10)
2016-05-04T20:26:33.4938388Z     at startup (node.js:129:16)
2016-05-04T20:26:33.4938388Z     at node.js:814:3

**Comment by jabjohanna** [comment]
Error in task npm and grunt ..  version Grunt 0.2.12 and Npm 0.5.18

2016-05-04T20:26:33.4938388Z C:\AgentRunProvisioning\tasks\Npm\0.2.12\npmtask.js:3
2016-05-04T20:26:33.4938388Z const path = require('path');
2016-05-04T20:26:33.4938388Z ^^^^^
2016-05-04T20:26:33.4938388Z SyntaxError: Use of const in strict mode.
2016-05-04T20:26:33.4938388Z     at exports.runInThisContext (vm.js:73:16)
2016-05-04T20:26:33.4938388Z     at Module._compile (module.js:443:25)
2016-05-04T20:26:33.4938388Z     at Object.Module._extensions..js (module.js:478:10)
2016-05-04T20:26:33.4938388Z     at Module.load (module.js:355:32)
2016-05-04T20:26:33.4938388Z     at Function.Module._load (module.js:310:12)
2016-05-04T20:26:33.4938388Z     at Function.Module.runMain (module.js:501:10)
2016-05-04T20:26:33.4938388Z     at startup (node.js:129:16)
2016-05-04T20:26:33.4938388Z     at node.js:814:3

**Comment by ericsciple** [comment]
Did you manually upload the the task to your account? Or are you seeing this from the system updating your account? What is your agent version (agent\vsoagent.exe /version or check the capability in the admin UI for the agent pool).

**Comment by bryanmacfarlane** [comment]
This PR covers code that's rolling out to different scale units.  When our code rolls out to different scale units, it also carries a new runtime.  If you're getting that error, it typically means you're running code meant for the next sprint's rollout.  You can't take future code and run in your instance

https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md

**Pull request merged**
