### PR TITLE
Update AndroidSigning tasks

### PR DESCRIPTION
**Pull request by yacaovsnc**
1. Remove redundant debug lines - task library writes debug lines now
2. Check jarsigner on PATH first before looking in JAVA_HOME
3. Fail with clear message if JAVA_HOME is not set
4. Add additional tests around file input and jarsigner location

### CODE REVIEW

**Comment by madhurig** [comment]
Looks good to me.

**Comment by apacha** [comment]
I've updated to the newest version of the build-agent (vsts-agent-osx.10.11-x64-2.102.0) but unfortunately this broke my android signing step.

Although I've tried the following things to set the ANDROID_HOME variable, I still get the message 
`Processed logging command: ##vso[task.debug]ANDROID_HOME=undefined`:

- Added ANDROID_HOME to the path with `export ANDROID_HOME=/Users/alex/Library/Developer/Xamarin/android-sdk-macosx/` before calling env.sh
- Verified that .env contains the line `ANDROID_HOME=/Users/alex/Library/Developer/Xamarin/android-sdk-macosx/`
- Added ANDROID_HOME manually to runsvc.sh into the section `# insert anything to setup env when running as a service`
- Always restarting the service with `sudo ./svc.sh stop` and `sudo ./svc.sh start`
- I event added the path directly to the .path file (although this obviously does not provide the variable ANDROID_HOME).

I even went one step further and executing my own shell-script that performs:

```
#!/bin/bash
export ANDROID_HOME=/Users/alex/Library/Developer/Xamarin/android-sdk-macosx
echo $ANDROID_HOME
```
which outputs the proper path to verify that the environment-variable is set correctly.

Desperately, I ended up adding the variable into the build-configuration in VSTS:
screen shot 2016-06-19 at 18 11 11

which finally fixed my build step again. Is that the way, it is supposed to be?

**Comment by madhurig** [comment]
@apache: What you are doing is correct to publish the environment variable as a agent capability, the same steps work for me and I see the ANDROID_SDK capability on the agent. You can see this on the admin page for Agent Pools similar to this:
androidhome
Do you not see this capability on your agent? 

Thanks,
Madhuri

**Comment by apacha** [comment]
I've tried again today and for some reason it works now without specifying the variable in the build-configuration.

I verified that my agent has the capability: 
capture

If I remember correctly, it already had that capability earlier, still I needed the variable. I'm not sure what has changed. Maybe a restart of my Mac was required after upgrading the build-agent to 2.102.1 for all variables to take effect.

**Pull request merged**
