### PR TITLE
Update 'runsOn' to include Deployment Groups.

### PR DESCRIPTION
**Pull request by SamuelMcAravey-NVP**

### CODE REVIEW

**Comment by SamuelMcAravey-NVP** [comment]
See issue: #5097

**Comment by bishal-pdMSFT** [comment]
@SamuelMcAravey-NVP , these changes look good to me. In case, you are planning to merge this PR, please resolve conflicts before merging.

**Comment by bryanmacfarlane** [comment]
take or close

**Comment by bishal-pdMSFT** [comment]
Closing this as another PR is taking this up - #5786

**Pull request closed without merging**
