### PR TITLE
Fixed helpMarkDown typo in DotNetCoreCLI task

### PR DESCRIPTION
**Pull request by webster354**
The csproj wildcard path is missing an * character. It should be **/*.csproj.

### CODE REVIEW

**Comment by ds-ms** [comment]
@webster354 Good catch. Thanks for fixing it. :)

**Comment by ds-ms** [comment]
Also, if you already have a setup, do build the task once. By running `gulp build --task DotNetCoreCLI` in the root of vsts-tasks folder, to update the strings for localization.

**Comment by bishal-pdMSFT** [comment]
@ds-ms is this good to be merged?

**Comment by sachinma** [comment]
@ds-ms can you help in merging this after updating the task version

**Comment by ds-ms** [comment]
I'll pick up these changes in a different PR. Closing it.

**Pull request closed without merging**
