### PR TITLE
Upgrade typescript to 2.x and fix build issues

### PR DESCRIPTION
**Pull request by nigurr**
- Upgrade TS to 2.x

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
Not right now.  We're re-engineering in a feature branch.

**Comment by bryanmacfarlane** [comment]
Let's hold for 108.  I want to make sure 107 stabilizes and we consciously move to 2.0.  I will send communications to teams inline with Trevor's mail

**Comment by crilleberglund** [comment]
Any idea when this will be released? I work with a angular2 project that I am waiting to deploy. 
Dependencies to typescript 2.0.3

**Comment by chrber5** [comment]
Any idea when this will be released? I work with a angular2 project that I am waiting to deploy. 
Dependencies to typescript 2.0.3

**Pull request closed without merging**
