### PR TITLE
Powershell on target machine version V1 and window machine file copy …

### PR DESCRIPTION
**Pull request by rokmicrosoft**
…V1 in master

### CODE REVIEW

**Comment by rokmicrosoft** [comment]
Bringing this [PR ](https://github.com/Microsoft/vsts-tasks/pull/6941) changes in master

**Comment by chshrikh** [comment]
looks fine, post merge test the packing once

**Comment by kmkumaran** [comment]
Was there any bug fix done to initial telemetry change as part of #6941. There was once an issue debugged by @arjgupta.

**Comment by kmkumaran** [comment]
@rokmicrosoft - Can you check the CDP has test coverage for both these tasks specifically for the 1.x version.

**Comment by rokmicrosoft** [comment]
We have for test coverage in CDP [WindowsFileCopy]( https://mseng.visualstudio.com/VSOnline/_git/VSO?path=%2FDevTestLabs%2FTestsCommon%2FTests%2FTaskE2ETests.cs&version=GBmaster&line=515&lineStyle=plain&lineEnd=516&lineStartColumn=1&lineEndColumn=1) and [powershellontargetmachine](https://mseng.visualstudio.com/VSOnline/_git/VSO?path=%2FDevTestLabs%2FTestsCommon%2FTests%2FTaskE2ETests.cs&version=GBmaster&line=626&lineStyle=plain&lineEnd=627&lineStartColumn=1&lineEndColumn=1)

**Pull request merged**
