### PR TITLE
Fix grammar in maximumCpuCount string

### PR DESCRIPTION
**Pull request by AArnott**
"your" is possessive
"you're" is an abbreviation for "you are"

### CODE REVIEW

**Comment by ericsciple** [comment]
technically it's a contraction, not an abbreviation :)

**Comment by ericsciple** [comment]
nevermind, i'm wrong again :) - according to wiki
> In strict analysis, abbreviations should not be confused with contractions, acronyms, or initialisms, with which they share some semantic and phonetic functions, though all four are connoted by the term "abbreviation" in loose parlance. An abbreviation is a shortening by any method

i see another one in the same paragraph. i'll fix.

**Comment by ericsciple** [comment]
This is the generated file that is overwritten at build time. I merged a PR that fixes it in the source (task.json).

**Comment by AArnott** [comment]
Thanks, @ericsciple for the fix, and the wiki-lesson. I learned something too.

**Pull request closed without merging**
