### PR TITLE
Revert "[Gradle] Set working directory before fetching for gradle wrapper script"

### PR DESCRIPTION
**Pull request by DavidStaheli**
Reverts Microsoft/vsts-tasks#4506

### CODE REVIEW

**Comment by DavidStaheli** [comment]
@benabbon I had to revert the change.  I was informed that relative paths, such as for the Gradle Wrapper field, are resolved to be absolute paths by the build agent before the Gradle step runs.  So 1) this won't have an effect, and 2) if it did have an effect, it would likely break the builds of people who expect the Gradle Wrapper to be found relative to the default working directory, rather than a user-specified working directory.

**Comment by benabbon** [comment]
I see. What would you propose for making the task work with my project knowing the limitations?
My folders look like this : 
Android/Library/
                           gradlew
                           settings.gradle
                           build.gradle

**Comment by DavidStaheli** [comment]
You should be able to set the **Gradle Wrapper** field to `Android/Library/gradlew` and then set the **Working Directory** field to `Android/Library`.  Does that work for you?

**Comment by benabbon** [comment]
I tried your proposition. It's seems to work when related to the error above about the gradle wrapper. But I'm getting weird issues related to SDK being read-only. Such as : 

2017-06-19T17:01:26.1907142Z Exception while marshalling C:\Program Files (x86)\Android\android-sdk\system-images\android-25\google_apis\x86_64\package.xml. Probably the SDK is read-only
2017-06-19T17:01:26.1907142Z Exception while marshalling C:\Program Files (x86)\Android\android-sdk\tools\package.xml. Probably the SDK is read-only
2017-06-19T17:01:30.9741877Z Checking the license for package Solver for ConstraintLayout 1.0.2 in C:\Program Files (x86)\Android\android-sdk\licenses
2017-06-19T17:01:30.9741877Z License for package Solver for ConstraintLayout 1.0.2 accepted.
2017-06-19T17:01:30.9898139Z Preparing "Install Solver for ConstraintLayout 1.0.2 (revision: 1)".
2017-06-19T17:01:30.9898139Z Warning: Failed to read or create install properties file.
2017-06-19T17:01:30.9898139Z Checking the license for package ConstraintLayout for Android 1.0.2 in C:\Program Files (x86)\Android\android-sdk\licenses
2017-06-19T17:01:30.9898139Z License for package ConstraintLayout for Android 1.0.2 accepted.
2017-06-19T17:01:30.9898139Z Preparing "Install ConstraintLayout for Android 1.0.2 (revision: 1)".
2017-06-19T17:01:30.9898139Z Warning: Failed to read or create install properties file.
2017-06-19T17:01:31.0054376Z 
2017-06-19T17:01:31.0054376Z FAILURE: Build failed with an exception.
2017-06-19T17:01:31.0054376Z 
2017-06-19T17:01:31.0054376Z * What went wrong:
2017-06-19T17:01:31.0054376Z A problem occurred configuring project ':papyroidLib'.
2017-06-19T17:01:31.0054376Z > Failed to install the following SDK components:
2017-06-19T17:01:31.0054376Z   [ConstraintLayout for Android 1.0.2, Solver for ConstraintLayout 1.0.2]
2017-06-19T17:01:31.0054376Z   The SDK directory (C:\Program Files (x86)\Android\android-sdk) is not writeable,
2017-06-19T17:01:31.0054376Z   please update the directory permissions.

Do you know if these can be fixed? Or should I contact the account admin for these scenarios?

**Pull request merged**
