### PR TITLE
Users/yacao/javatasksfix

### PR DESCRIPTION
**Pull request by yacaovsnc**

### CODE REVIEW

**Comment by DavidStaheli** [comment]
Do we need to bump the versions +2 instead of +1 so that these changes will replace what is in the S105 deployment?

**Comment by yacaovsnc** [comment]
+1 is enough - I verified all versions here is one level higher than what's in M105, someone must have already bumped version once before.

**Comment by DavidStaheli** [comment]
Looks good!

**Comment by madhurig** [comment]
Looks good to me.

**Pull request merged**
