### PR TITLE
Fix packer custom template build issue

### LINKED ISSUE #4865: Packer Build Task – For User provided template Artifacts referenced in the template File are not available
### Steps to replicate
* Use a User provided template which references other files or folder like a file provisioner and run the build or release. files / folders could be referenced in the packer template as follows
  ```json
  {
      "type": "ansible-local",
      "playbook_file": "{{ template_dir }}/phpapp-packer-ansible-provisioner.yml"
  }
   ```
   OR
  ```json
   {
      "type": "file",
      "source": "{{ template_dir }}/data.php",
      "destination": "/tmp/data.php"
    },
  ```

* Build Will fail and throw an error

### Output from VSTS log

* template file getting copied and not other artifacts

  ```sh
  Copying original template from /opt/vsts/work/r1/a/RockM-Dashboard-Build/repofiles/build-files/packer-files/phpapp-packerpreviewtask.json to temporary location /opt/vsts/work/_temp/1500914709724
   2017-07-24T16:45:10.6603660Z Copied template file to a temporary location: /opt/vsts/work/_temp/1500914709724"
  ```

*  Error being thrown
    ```sh
     Bad source '/opt/vsts/work/_temp/1500914709724/../../data.php'
    ```

* Sample template
   ```json
   {
  "variables": {
    "tenant_id": "{{env `ARM_TENANT_ID`}}",
    "client_id": "{{env `ARM_CLIENT_ID`}}",
    "client_secret": "{{env `ARM_CLIENT_SECRET`}}",
    "resource_group": "{{env `ARM_RESOURCE_GROUP`}}",
    "storage_account": "{{env `ARM_STORAGE_ACCOUNT`}}",
    "subscription_id": "{{env `ARM_SUBSCRIPTION_ID`}}"
  },
  "builders": [{
    "type": "azure-arm",

    "client_id": "{{user `client_id`}}",
    "client_secret": "{{user `client_secret`}}",
    "resource_group_name": "{{user `resource_group`}}",
    "storage_account": "{{user `storage_account`}}",
    "subscription_id": "{{user `subscription_id`}}",
    "tenant_id": "{{user `tenant_id`}}",

    "capture_container_name": "images",
    "capture_name_prefix": "packer",

    "os_type": "Linux",
    "image_publisher": "Canonical",
    "image_offer": "UbuntuServer",
    "image_sku": "16.04.0-LTS",


    "location": "West US",
    "vm_size": "Standard_A2"
  }],
  "provisioners": [

  {
    "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
    "inline": [
      "apt-get update",
      "apt-get upgrade -y",
      "apt-get install ansible -y"

    ],
    "inline_shebang": "/bin/sh -x",
    "type": "shell"
  },
    {
      "type": "file",
      "source": "{{ template_dir }}/../../data.php",
      "destination": "/tmp/data.php"
    },
    {
      "type": "file",
      "source": "{{ template_dir }}/../../drill.html",
      "destination": "/tmp/drill.html"
    },
    {
      "type": "file",
      "source": "{{ template_dir }}/../../index.html",
      "destination": "/tmp/index.html"
    },    
    {
      "type": "file",
      "source": "{{ template_dir }}/../../dist",
      "destination": "/tmp/dist"
    },

  {
      "type": "ansible-local",
      "playbook_file": "{{ template_dir }}/phpapp-packer-ansible-provisioner.yml"
  },
  {
    "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
    "inline": [
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    ],
    "inline_shebang": "/bin/sh -x",
    "type": "shell"
  }
  ]

}

   ```

### PR DESCRIPTION
**Pull request by maniSbindra**
These are changes to fix #4865 .

Changes:
* Custom packer template not copied to temporary directory
* Removed 2 tests which were validating copy of custom template to temporary directory
* Modified mock values for custom template tests. Mocked values were earlier pointing to the temporary directory

### CODE REVIEW

**Comment by bishal-pdMSFT** [comment]
Looks good. Please test manually once for custom template.

**Comment by maniSbindra** [comment]
@bishal-pdMSFT  : tested manually by uploading extension. Task executed successfully.

```sh
017-07-28T09:37:25.0105440Z Running packer validate command to ensure template is valid
2017-07-28T09:37:25.0151470Z [command]/opt/vsts/work/_temp/1501234643779/packer/packer validate /opt/vsts/work/r1/a/RockM-Dashboard-Build/repofiles/build-files/packer-files/phpapp-packerpreviewtask-fixed.json
2017-07-28T09:37:25.8215070Z Template validated successfully.
2017-07-28T09:37:25.8278850Z Running packer build command. Waiting for it to finish...
2017-07-28T09:37:25.8331590Z [command]/opt/vsts/work/_temp/1501234643779/packer/packer build -force /opt/vsts/work/r1/a/RockM-Dashboard-Build/repofiles/build-files/packer-files/phpapp-packerpreviewtask-fixed.json
2017-07-28T09:37:25.8345910Z 
2017-07-28T09:37:25.8374190Z 
2017-07-28T09:37:25.9107460Z [1;32mazure-arm output will be in this color.[0m
```

```sh
2017-07-28T09:51:17.3178330Z [1;32m==> azure-arm: Uploading /opt/vsts/work/r1/a/RockM-Dashboard-Build/repofiles/build-files/packer-files/../../data.php => /tmp/data.php
``` 

```sh
2017-07-28T10:04:23.0642110Z packer build completed.
2017-07-28T10:04:23.0770840Z ##[section]Finishing: Build immutable image
```

**Comment by bishal-pdMSFT** [comment]
please increment task patch version.

**Comment by bishal-pdMSFT** [comment]
Also this needs to go to releases/M121 branch. do you want to raise for PR for that as well?

**Comment by bishal-pdMSFT** [comment]
Do you have permission to merge PRs?

**Comment by maniSbindra** [comment]
Have incremented Patch version in task.json and task.lock.json.

**Comment by maniSbindra** [comment]
I do not have merge PR permissioins

**Comment by bishal-pdMSFT** [comment]
okay, then i will merge it?

**Pull request merged**
