### PR TITLE
(issue #946) visual studio command-line build vnext step (devenv.com)

### PR DESCRIPTION
**Pull request by jmacnett**
issue #946

Functional, configurable vnext step allowing the user to invoke devenv.com and build via visual studio, instead of msbuild.  This adds back in support for project types that msbuild doesn't handle (SSRS projects, for example).

### CODE REVIEW

**Comment by jmacnett** [comment]
did that.  enjoy.

**Comment by mmajcica** [comment]
@jmacnett You did a good job, especially around the effort of going trough the invocation output and trying to match and handle errors. I do see however a place for some minor improvements. I will try to draft and test them and then I'll make a pull request to your branch.

Thanks for sharing

**Comment by bryanmacfarlane** [comment]
I think we are going to support this but in a slightly different way.  We want an input on the existing Visual Studio Build task that says use devenv (defaults to false).  If true, it takes the variant path running code similar to above.  We don't want another task.

The current VS build task is essentially still running msbuild but the purpose of it is to location the proper version of msbuild via the specified VS version.

Do you want to take a crack at that PR?  We can help CR, test, etc...

Also, take a look at how we're writing L0 tasks via mocking.  The goal is to exercise every arc/function of the script without actually doing the work and runs sub second.

**Comment by jmacnett** [comment]
I'm not opposed to implementing it in that fashion, if that's the desired approach.  I can certainly take a crack at modifying the existing visual studio build task as described. 

With that said, how set is your team on this approach?  My concern with having the two paths within that same task is that the command-line arguments for devenv vs msbuild are pretty divergent, beyond a point.  In fact, it almost seems that the use-visual-studio-to-select-a-version-of-msbuild logic could be in the MSBuild task template, in parallel w/ the msbuild version selection UI, and the devenv/VS build option could be it's own task option.

Again, I'm just asking...seems like a more intuitive approach to me.  I am willing to spend some time on this in either case, as I'd like to see it become part of the standard vnext offerings.  Thanks!

**Comment by bryanmacfarlane** [comment]
We're pretty set.  We don't want a proliferation of tasks.  Switching on which cmd line to call us a minor implementation detail. 

When you have both tasks that are at a glance the same ( vs / devenv ) it's confusing which to pick.  If you have one then inside the context of giving inputs to the task we can offer guidance.

Create a separate PR and I can pair you up with a dev on this side

**Comment by xhead** [comment]
> Create a separate PR and I can pair you up with a dev on this side

Did this die on the vine?

**Comment by bryanmacfarlane** [comment]
@jmacnett ??

**Comment by rrober07** [comment]
Where does this task stand...has it been address? completed?

**Comment by xhead** [comment]
I started working on this code when I first posted my question. I did make some progress but it isn't ready for putting into a pull request yet. I haven't touched it for a number of weeks now (I took another track in my project shortly after this thread went silent).

I was kinda waiting to see if someone in the team might be assigned to this and give me the guidance that was offered to jmacknett. Reading it again now, I see that you had asked him to created a PR first.

If you want to see what I've done so far, I can do a PR.

Mike
________________________________

**Comment by rrober07** [comment]
Has this been completed? where can I get the copy to update our TFS2015 update 3...

thanks

**Comment by xhead** [comment]
I haven’t created a pull request for this yet, I hadn’t heard that you wanted one from me. Sorry about that.

Last I checked, I needed to merge in a bunch of changes before I was able to get my change in. What is your timeline for this release? If I did this on the weekend, would it be too late?


Mike Diehl <sip:miked@imaginet.com>
Practice Lead for Databases and Business Intelligence  |  Imaginet  |  [cid:image004.png@01CEF68D.19A9C0A0] <http://www.twitter.com/justimaginet>  [cid:image005.jpg@01CEF68D.19A9C0A0] <http://www.facebook.com/justimaginet>  [cid:image006.png@01CEF68D.19A9C0A0] <http://www.linkedin.com/companies/imaginet>
miked@imaginet.com<mailto:miked@imaginet.com>  |  P 204.977.6968  |  C 204.781.7166 | 210 – 233 Portage Ave.  |  Winnipeg, MB  |  R3B 2A7

[cid:image007.png@01CEF68D.19A9C0A0]<http://www.imaginet.com/>
ideas. technology. imagine<http://www.imaginet.com/>.
subscribe<http://learn.imaginet.com/subscribe-to-newsletter.html> to our newsletter

**Comment by rrober07** [comment]
no problem...This weekend would be fine...let me know

Thanks

**Comment by rrober07** [comment]
Where you able to get those changes finished last weekend?  Let me
know...and what I need to do to get this on my TFS2015 server.

Thanks
Richard

**Comment by bryanmacfarlane** [comment]
The right fix is to add a bool input to the VSBuild task to use devenv.exe.  If you want a PR then that's the right approach.

**Comment by rrober07** [comment]
which branch should I request?

**Comment by xhead** [comment]
HM, the way I built mine was to add a third choice, devenv.com, to the two msbuild choices.

Sent from my Windows Phone
________________________________

**Comment by bryanmacfarlane** [comment]
Right.  And that's problematic because when someone uses the mainline default option of msbuild (we default to the lighter weight cmdline approach) and realize for some reason they want to switch to using devenv (there were unfortunately some scenarios that only work from VS), they shouldn't have to remove a step, add a new step, and re-input all the data.  They should just flip a toggle.

**Comment by rrober07** [comment]
What branch is your change in...so I can pull that?

**Comment by xhead** [comment]
I still haven't checked it in

Sent from my Windows Phone
________________________________

**Comment by rrober07** [comment]
What branch should I request to pull for this switch?

On Tue, Sep 27, 2016 at 10:03 AM, Bryan MacFarlane <notifications@github.com

**Comment by xhead** [comment]
I don't have it in yet

Sent from my Windows Phone
________________________________

**Comment by rrober07** [comment]
I am assuming this has been fixed or moved to the TFS15 version coming since it has been closed

**Comment by rrober07** [comment]
bryan,

what ever happened to VSBuild using Devenv?   has it been implemented?  we
can not build SSRS,SSIS,SSAS with MSBuild? This is a roadblock for our
team...how have others solved for builds in TFS2015?

Richard

**Comment by psandhu79** [comment]
what state is this ? when might we see this ?

**Comment by xhead** [comment]
I've abandoned it. It's easier to write a command task than to update this code.

Sent from my Windows Phone
________________________________

**Comment by psandhu79** [comment]
But is there an easy way of detecting where the visual studio is installed on the machine if using on-prem agents or hosted ones ?

**Comment by xhead** [comment]
I've used an on prem agent

Sent from my Windows Phone
________________________________

**Comment by xhead** [comment]
There are some registry keys with install locations for vs. The source code for this task uses then to find msbuild.

Sent from my Windows Phone
________________________________

**Pull request closed without merging**
